import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#6ad4f4',
        'outline': '#ae8883',
        'on-primary': '#690006',
        'tertiary': '#6ad4f4',
        'secondary-container': '#474746',
        'surface-dim': '#131313',
        'on-error-container': '#ffdad6',
        'inverse-primary': '#c00014',
        'on-tertiary-fixed': '#001f27',
        'on-secondary-container': '#b7b5b4',
        'surface-container-high': '#2a2a2a',
        'surface-container-low': '#1c1b1b',
        'on-primary-fixed': '#410002',
        'background': '#131313',
        'outline-variant': '#5e3f3c',
        'on-error': '#690005',
        'error-container': '#93000a',
        'surface-variant': '#353534',
        'on-tertiary': '#003642',
        'on-secondary-fixed': '#1c1b1b',
        'on-primary-fixed-variant': '#93000c',
        'primary-fixed': '#ffdad6',
        'error': '#ffb4ab',
        'surface-container': '#201f1f',
        'tertiary-container': '#229dbc',
        'primary-fixed-dim': '#ffb4ab',
        'secondary-fixed-dim': '#c8c6c5',
        'primary': '#ffb4ab',
        'primary-container': '#ff544b',
        'inverse-on-surface': '#313030',
        'on-secondary-fixed-variant': '#474746',
        'on-background': '#e5e2e1',
        'surface-container-highest': '#353534',
        'inverse-surface': '#e5e2e1',
        'surface-bright': '#3a3939',
        'on-surface': '#e5e2e1',
        'tertiary-fixed': '#b3ebff',
        'secondary-fixed': '#e5e2e1',
        'on-primary-container': '#5c0005',
        'on-tertiary-container': '#002e3a',
        'on-surface-variant': '#e7bcb8',
        'on-tertiary-fixed-variant': '#004e5f',
        'on-secondary': '#313030',
        'surface': '#131313',
        'secondary': '#c8c6c5',
        'surface-container-lowest': '#0e0e0e',
        'surface-tint': '#ffb4ab',
        'cyber-red': '#FF3131',
      },
      borderRadius: {
        DEFAULT: '2px',
        lg: '4px',
        xl: '8px',
        full: '9999px',
      },
      spacing: {
        gutter: '32px',
        'margin-desktop': '80px',
        'margin-mobile': '24px',
        unit: '8px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'display-xl': ['Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'label-mono': ['"Geist Mono"', 'monospace'],
        'headline-md': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-xl': ['80px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-mono': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}

export default config
