export interface PortfolioEntry {
  url: string
  platform: string
  company: string
  contribution: string
  active: 'yes' | 'no' | ''
}

export const portfolioData: PortfolioEntry[] = [
  { url: 'https://mavencommunityhealth.org/', platform: 'WordPress', company: 'Growmodo', contribution: '95%', active: 'yes' },
  { url: 'https://www.humanpossible.com/', platform: 'Webflow', company: 'Growmodo', contribution: '90%', active: 'yes' },
  { url: 'https://land.tech/', platform: 'HubSpot', company: 'Growmodo', contribution: '40%', active: 'yes' },
  { url: 'https://www.gemspire.org/', platform: 'Wix', company: 'Growmodo', contribution: '90%', active: 'yes' },
  { url: 'https://www.gotmoxiehealth.com/', platform: 'Squarespace', company: 'Growmodo', contribution: '90%', active: 'yes' },
  { url: 'https://anchordbc-jjarbo.wixstudio.com/my-site-1-1', platform: 'Wix', company: 'Growmodo', contribution: '40%', active: 'yes' },
  { url: 'https://topshelfbartenders.squarespace.com/', platform: 'Squarespace', company: 'Growmodo', contribution: '20%', active: 'yes' },
  { url: 'panama', platform: 'HTML', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://www.pilame.nl/', platform: 'Webflow', company: 'Growmodo', contribution: '60%', active: 'yes' },
  { url: 'http://thechurchatrb.com/', platform: 'Webflow', company: 'Growmodo', contribution: '80%', active: 'yes' },
  { url: 'https://www.writtenbyluna.nl/', platform: 'Webflow', company: 'Growmodo', contribution: '20%', active: 'yes' },
  { url: 'https://ainnovators.ch/', platform: 'WordPress', company: 'Growmodo', contribution: '80%', active: 'yes' },
  { url: 'https://alpinemar.com/', platform: 'WordPress', company: 'Growmodo', contribution: '20%', active: 'yes' },
  { url: 'https://www.thetopshelfbartenders.com/', platform: 'Squarespace', company: 'Growmodo', contribution: '100%', active: 'yes' },
  { url: 'https://van8887.wixstudio.com/ar-meats', platform: 'Wix', company: 'Growmodo', contribution: '80%', active: 'yes' },
  { url: 'https://heysweetcheeks.co/', platform: 'Shopify', company: 'Growmodo', contribution: '60%', active: 'yes' },
  { url: 'https://mars-trading.dk/', platform: 'Webflow', company: 'Growmodo', contribution: '95%', active: 'yes' },
  { url: 'https://www.motopoint.mt/', platform: 'WordPress', company: 'Growmodo', contribution: '30%', active: 'yes' },
  { url: 'https://thebrandsource.com/', platform: 'WordPress', company: 'Growmodo', contribution: '70%', active: 'yes' },
  { url: 'https://www.gofar.co/', platform: 'WordPress', company: 'Growmodo', contribution: '50%', active: 'yes' },
  { url: 'https://www.gruberianeselli.ch/', platform: 'WordPress', company: 'Growmodo', contribution: '80%', active: 'yes' },
  { url: 'https://www.citadelplc.com/', platform: 'WordPress', company: 'Growmodo', contribution: '10%', active: 'yes' },
  { url: 'https://engel-zofingen.ch/en/', platform: 'WordPress', company: 'Growmodo', contribution: '30%', active: 'yes' },
  { url: 'https://ruhdental.com/', platform: 'WordPress', company: 'Growmodo', contribution: '70%', active: 'yes' },
  { url: 'https://www.splendidyachting.com/', platform: 'WordPress', company: 'Growmodo', contribution: '40%', active: 'yes' },
  { url: 'https://arrotek.com/', platform: 'WordPress', company: 'Growmodo', contribution: '10%', active: 'yes' },
  { url: 'https://www.drakeroadortho.com/', platform: 'Squarespace', company: 'Growmodo', contribution: '40%', active: 'yes' },
  { url: 'https://www.staffcenturion.com/', platform: 'WordPress', company: 'Growmodo', contribution: '85%', active: 'yes' },
  { url: 'https://www.tarponspringsdistillery.net/', platform: 'WordPress', company: 'Growmodo', contribution: '85%', active: 'yes' },
  { url: 'https://keepclimbingsb.org/', platform: 'WordPress', company: 'Growmodo', contribution: '80%', active: 'yes' },
  { url: 'lesactati', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://fortifyrestoration.com/', platform: 'WordPress', company: 'Growmodo', contribution: '30%', active: 'yes' },
  { url: 'finanzsofa', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://emissarywealth.com/', platform: 'WordPress', company: 'Growmodo', contribution: '95%', active: 'yes' },
  { url: 'milltowncapital', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'somethingspecialpresentations', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'thechallery', platform: 'WordPress', company: 'Growmodo', contribution: '70%', active: 'yes' },
  { url: 'https://berkshirebec.org/', platform: 'WordPress', company: 'Growmodo', contribution: '60%', active: 'yes' },
  { url: 'countrywidepublicadjuster', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'cyriusmediagroup', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'joe-sansone', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'logannewell', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'zentek', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'elevatespo1stg', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'intellect', platform: 'WordPress', company: 'Growmodo', contribution: '60%', active: 'yes' },
  { url: 'jmacgprd', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://www.m2m.media/', platform: 'Webflow', company: 'Growmodo', contribution: '30%', active: 'yes' },
  { url: 'https://lantohealth.com/', platform: 'Shopify', company: 'Growmodo', contribution: '30%', active: 'yes' },
  { url: 'https://www.rentava.ch/en/', platform: 'WordPress', company: 'Growmodo', contribution: '10%', active: 'yes' },
  { url: 'https://nwportlandmassage.com/', platform: 'WordPress', company: 'Growmodo', contribution: '95%', active: 'yes' },
  { url: 'https://sdcatholic.org/', platform: 'WordPress', company: 'Growmodo', contribution: '30%', active: 'yes' },
  { url: 'https://www.sendcloud.com/', platform: 'WordPress', company: 'Growmodo', contribution: '60%', active: 'yes' },
  { url: 'solisz-energy', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://tierhotelmamamo.de/', platform: 'WordPress', company: 'Growmodo', contribution: '50%', active: 'yes' },
  { url: 'https://tindofnorway.no/', platform: 'Shopify', company: 'Growmodo', contribution: '60%', active: 'yes' },
  { url: 'https://www.vaxsocial.com/', platform: 'Webflow', company: 'Growmodo', contribution: '70%', active: 'yes' },
  { url: 'https://wonderboo.com/en', platform: 'Shopify', company: 'Growmodo', contribution: '30%', active: 'yes' },
  { url: 'happyfresh', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://www.meenadchi.com/', platform: 'HTML', company: 'Growmodo', contribution: '10%', active: 'yes' },
  { url: 'mokki', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'nakedroot', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://rowebeef.com/', platform: 'Shopify', company: 'Growmodo', contribution: '80%', active: 'yes' },
  { url: 'https://a1trusses.com/', platform: 'WordPress', company: 'Growmodo', contribution: '70%', active: 'yes' },
  { url: 'https://www.decks-docks.com/', platform: 'WordPress', company: 'Growmodo', contribution: '70%', active: 'yes' },
  { url: 'learnico-the-most-popular-courses', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'taplio-blog', platform: 'HTML', company: 'Growmodo', contribution: '85%', active: 'yes' },
  { url: 'https://www.aquatabs.com/', platform: 'WordPress', company: 'Growmodo', contribution: '90%', active: 'yes' },
  { url: 'https://3deksperten.dk/', platform: 'WordPress', company: 'Growmodo', contribution: '60%', active: 'yes' },
  { url: 'alisonjprince', platform: 'WordPress', company: 'Growmodo', contribution: '100%', active: 'yes' },
  { url: 'https://www.mossbuildinganddesign.com/', platform: 'HubSpot', company: 'Growmodo', contribution: '30%', active: 'yes' },
  { url: 'https://empire-parking.com/', platform: 'WordPress', company: 'Growmodo', contribution: '30%', active: 'yes' },
  { url: 'bekin', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://baxmanns.de/', platform: 'Squarespace', company: 'Growmodo', contribution: '60%', active: 'yes' },
  { url: 'bravura-education', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://stake.world/', platform: 'Shopify', company: 'Growmodo', contribution: '30%', active: 'yes' },
  { url: 'https://the345.co.uk/', platform: 'WordPress', company: 'Growmodo', contribution: '75%', active: 'yes' },
  { url: 'plaympe', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://relationallife.com/', platform: 'WordPress', company: 'Growmodo', contribution: '80%', active: 'yes' },
  { url: 'https://www.bravura.edu.au/', platform: 'WordPress', company: 'Growmodo', contribution: '80%', active: 'yes' },
  { url: 'dxbperfume', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://buy.forevergreenherbal.com/', platform: 'WordPress', company: 'Growmodo', contribution: '95%', active: 'yes' },
  { url: 'https://drga.org/', platform: 'HTML', company: 'Growmodo', contribution: '10%', active: 'yes' },
  { url: 'provisions-williamstown', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://www.therecoveryvillage.com/', platform: 'WordPress', company: 'Growmodo', contribution: '70%', active: 'yes' },
  { url: 'https://magneticme.com/', platform: 'Shopify', company: 'Growmodo', contribution: '30%', active: 'yes' },
  { url: 'https://workscout.in/', platform: 'WordPress', company: 'Growmodo', contribution: '70%', active: 'yes' },
  { url: 'greenchoice', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'p&b', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://joywholefoods.com.au/', platform: 'Shopify', company: 'Growmodo', contribution: '60%', active: 'yes' },
  { url: 'https://sweetpeasco.com/', platform: 'Shopify', company: 'Growmodo', contribution: '40%', active: 'yes' },
  { url: 'https://the-klutch.com/', platform: 'WordPress', company: 'Growmodo', contribution: '70%', active: 'yes' },
  { url: 'https://thecreativecompany.us/', platform: 'Shopify', company: 'Growmodo', contribution: '40%', active: 'yes' },
  { url: 'https://www.glenglassaugh.com/', platform: 'WordPress', company: 'Growmodo', contribution: '50%', active: 'yes' },
  { url: 'https://joinmamba.com/', platform: 'WordPress', company: 'Growmodo', contribution: '100%', active: 'yes' },
  { url: 'https://itiengineering.com/', platform: 'WordPress', company: 'Growmodo', contribution: '10%', active: 'yes' },
  { url: 'syncfab', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'mishnah', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'psgglobal', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'david-joseph', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'luise-catering', platform: 'Wix', company: 'Growmodo', contribution: '', active: '' },
  { url: 'synlighet', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://www.itsmhub.com.au/', platform: 'Shopify', company: 'Growmodo', contribution: '70%', active: 'yes' },
  { url: '911cancerclaim', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'newlevelgold', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'snuggs', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'braxit', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://dayangjian.com/home.html', platform: 'HTML', company: 'Growmodo', contribution: '20%', active: 'yes' },
  { url: 'https://foodiesfriendly.com.au/', platform: 'WordPress', company: 'Growmodo', contribution: '100%', active: 'yes' },
  { url: 'https://www.rawk9.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '100%', active: 'no' },
  { url: 'https://maximusfranchise.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '100%', active: 'no' },
  { url: 'https://gofirstleaderpodcast.kinsta.cloud/', platform: 'WordPress', company: 'Growmodo', contribution: '100%', active: 'yes' },
  { url: 'https://shop.laureaextensions.de', platform: 'Shopify', company: 'Growmodo', contribution: '20%', active: 'yes' },
  { url: 'https://vendingsolutions.io/', platform: 'WordPress', company: 'Growmodo', contribution: '60%', active: 'yes' },
  { url: 'https://dgtlgroup.io/', platform: 'WordPress', company: 'Growmodo', contribution: '90%', active: 'yes' },
  { url: 'jmacg', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://www.mugshott.coffee/', platform: 'Webflow', company: 'Growmodo', contribution: '80%', active: 'yes' },
  { url: 'https://yamato.club/', platform: 'HTML', company: 'Growmodo', contribution: '100%', active: 'yes' },
  { url: 'https://callforspeakers.com/', platform: 'WordPress', company: 'Growmodo', contribution: '100%', active: 'yes' },
  { url: 'forklifts', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://storymight.com', platform: 'WordPress', company: 'Growmodo', contribution: '100%', active: 'yes' },
  { url: 'https://warrcloud.seventyseven.dev/', platform: 'WordPress', company: 'Growmodo', contribution: '100%', active: 'yes' },
  { url: 'hallmarksecure', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://livevillamiami.com/', platform: 'WordPress', company: 'Growmodo', contribution: '100%', active: 'yes' },
  { url: 'https://tacalientemex.com/', platform: 'WordPress', company: 'Growmodo', contribution: '10%', active: 'yes' },
  { url: 'https://major-agency.com/', platform: 'WordPress', company: 'Growmodo', contribution: '', active: 'yes' },
  { url: 'https://kariopsal.com/', platform: 'Squarespace', company: 'Growmodo', contribution: '10%', active: 'yes' },
  { url: 'https://hg.stanleymortgagegroup.com', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'lenoxpharmacy', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'elegance-living', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'thechallery.com', platform: 'WordPress', company: 'Growmodo', contribution: '100%', active: 'yes' },
  { url: 'https://www.the5fg.com/miami-carlo.html', platform: 'HTML', company: 'Growmodo', contribution: '80%', active: 'yes' },
  { url: 'shaarhachaim', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'tellmeaboutyourdreamhome', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'weiswesternwear', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'gustensun', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://lp.dreamhousemortgages.com', platform: 'WordPress', company: 'Growmodo', contribution: '100%', active: 'yes' },
  { url: 'christophenicolasbiot-2024', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://goldenplush.com/', platform: 'WordPress', company: 'Growmodo', contribution: '100%', active: 'yes' },
  { url: 'https://www.realcleardaf.com/', platform: 'WordPress', company: 'Growmodo', contribution: '60%', active: 'yes' },
  { url: 'https://fidabio.com', platform: 'WordPress', company: 'Growmodo', contribution: '30%', active: 'yes' },
  { url: 'https://shop.fidabio.com/', platform: 'WordPress', company: 'Growmodo', contribution: '70%', active: 'yes' },
  { url: 'https://residential.levelrealty.com', platform: 'WordPress', company: 'Growmodo', contribution: '60%', active: 'yes' },
  { url: 'chizukseries', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'smartmtg-2023', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://blogazoi.com/', platform: 'WordPress', company: 'Growmodo', contribution: '10%', active: 'yes' },
  { url: 'exoticsatthepointe', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'bridgetrealty', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'chappe.studio', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'thecouch.health', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'serit-2023', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://annahermida.com/', platform: 'WordPress', company: 'Growmodo', contribution: '90%', active: 'yes' },
  { url: 'tailorsunionmemphis', platform: 'WordPress', company: 'Growmodo', contribution: '90%', active: 'yes' },
  { url: 'careerchimp-2023', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://gattaco.com/', platform: 'WordPress', company: 'Growmodo', contribution: '90%', active: 'yes' },
  { url: 'swiftbooks', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://casamarbeachpompano.com/', platform: 'WordPress', company: 'Growmodo', contribution: '60%', active: 'yes' },
  { url: 'https://saltyrentalsnsb.com/', platform: 'WordPress', company: 'Growmodo', contribution: '100%', active: 'yes' },
  { url: 'ecophantauto', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://www.houz.no/', platform: 'WordPress', company: 'Growmodo', contribution: '40%', active: 'yes' },
  { url: 'https://smartmfg.io', platform: 'WordPress', company: 'Growmodo', contribution: '70%', active: 'yes' },
  { url: 'technique-de-vente', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'eagle-academy', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'peakptrochester', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://www.cawleypt.net/', platform: 'WordPress', company: 'Growmodo', contribution: '80%', active: 'yes' },
  { url: 'pegasus-luxury', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'podigy', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'bgk-solutions', platform: 'Squarespace', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://thegrowthbully.com/', platform: 'Webflow', company: 'Growmodo', contribution: '10%', active: 'yes' },
  { url: 'partingtonps', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://www.fluffywincasino.com/', platform: 'Next.js', company: 'Growmodo', contribution: '5%', active: 'yes' },
  { url: 'https://www.vitalyc.com/', platform: 'WordPress', company: 'Growmodo', contribution: '70%', active: 'yes' },
  { url: 'rennieandrose', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://op-invests.com/', platform: 'WordPress', company: 'Growmodo', contribution: '80%', active: 'yes' },
  { url: 'checkmate.health', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://sortland-havn.no/', platform: 'WordPress', company: 'Growmodo', contribution: '80%', active: 'yes' },
  { url: 'https://areadonline.com/', platform: 'WordPress', company: 'Growmodo', contribution: '30%', active: 'yes' },
  { url: 'https://www.mandourlaw.com/', platform: 'WordPress', company: 'Growmodo', contribution: '10%', active: 'yes' },
  { url: 'norsevikingsoap', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'mtmu', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'traderlion', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'sfloridahouses', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'phoenixwall', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://ridgercapital.com/', platform: 'WordPress', company: 'Growmodo', contribution: '60%', active: 'yes' },
  { url: 'memorol', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'spki', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'torpogco', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'gnosisbylesaffre', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'hoshaakon', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'lawhousemiami', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'melusinewines', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'ahamnarorbuer', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'itpartner', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'rmpfinishes', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'torskenettverket', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'slicker-beaut', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'maxone', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'dolvi', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'assima', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'lofotstrikk', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'graftsocial', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'gouldfarm', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'liamfoundation', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://suburbanmed.net/', platform: 'WordPress', company: 'Growmodo', contribution: '30%', active: 'yes' },
  { url: 'rentslingshotfl', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'designharvest', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://377builders.com/', platform: 'WordPress', company: 'Growmodo', contribution: '70%', active: 'yes' },
  { url: 'https://bousquetmountain.com/', platform: 'WordPress', company: 'Growmodo', contribution: '60%', active: 'yes' },
  { url: 'minus10andcounting', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://guidosfreshmarketplace.com', platform: 'WordPress', company: 'Growmodo', contribution: '10%', active: 'yes' },
  { url: 'themixologistsclub', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'blilaererdavel', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://www.exploring.ipu.co.uk/', platform: 'WordPress', company: 'Growmodo', contribution: '100%', active: 'yes' },
  { url: 'https://luxehomestaginganddesign.com/', platform: 'WordPress', company: 'Growmodo', contribution: '60%', active: 'yes' },
  { url: 'digitalmappe', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://framsikt.no/', platform: 'WordPress', company: 'Growmodo', contribution: '30%', active: 'yes' },
  { url: 'thealtitudelife', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'hhmprod', platform: 'HTML', company: 'Growmodo', contribution: '', active: '' },
  { url: 'mardergroup', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://dr-chereath.de/', platform: 'WordPress', company: 'Growmodo', contribution: '10%', active: 'yes' },
  { url: 'https://momentumm.co', platform: 'Webflow', company: 'Growmodo', contribution: '30%', active: 'yes' },
  { url: 'torsk', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'wallbeautyshop', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: '420dc', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'wholesale.ecsbrands', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'newcreations', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'msquaremarketing', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'badex-bau', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'aiirconsulting', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'sivatromso', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://designparken.com/', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://drshape.net/', platform: 'Shopify', company: 'Growmodo', contribution: '60%', active: 'yes' },
  { url: 'majordigitalmedia', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'daisystonestudio', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'spinoffyarnshop', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'missionberkshires', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://greylockworks.com/', platform: 'WordPress', company: 'Growmodo', contribution: '30%', active: 'yes' },
  { url: 'pizzeriaboema', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'stockbridge-ma', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://brianorourkecarpentry.com/', platform: 'WordPress', company: 'Growmodo', contribution: '40%', active: 'yes' },
  { url: 'npcberkshires', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://frankiesitaliano.com/', platform: 'WordPress', company: 'Growmodo', contribution: '40%', active: 'yes' },
  { url: 'foundationyoga', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://excelsiorintegrated.com/', platform: 'WordPress', company: 'Growmodo', contribution: '25%', active: 'yes' },
  { url: 'elegantstitchesinc', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://decumanusgreen.com/', platform: 'WordPress', company: 'Growmodo', contribution: '40%', active: 'yes' },
  { url: 'camphalfmoon', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'barneystein', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'agonadvisors', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://a-1securityonline.com/', platform: 'WordPress', company: 'Growmodo', contribution: '70%', active: 'yes' },
  { url: 'christopherjonesphoto', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'ta-hair-i', platform: 'Shopify', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://topspeedracing.co.uk', platform: 'WordPress', company: 'Growmodo', contribution: '100%', active: 'yes' },
  { url: 'https://www.normartrading.no/', platform: 'WordPress', company: 'Growmodo', contribution: '60%', active: 'yes' },
  { url: 'energisystemer', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://elbowvalley.com/', platform: 'WordPress', company: 'Growmodo', contribution: '30%', active: 'yes' },
  { url: 'ericsimpsonrealty', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'crent', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://lyfefuel.com/', platform: 'Shopify', company: 'Growmodo', contribution: '60%', active: 'yes' },
  { url: 'https://fuseventure.partners/', platform: 'WordPress', company: 'Growmodo', contribution: '30%', active: 'yes' },
  { url: 'https://cataarts.org/', platform: 'WordPress', company: 'Growmodo', contribution: '30%', active: 'yes' },
  { url: 'fundayout', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://liftme.no/', platform: 'WordPress', company: 'Growmodo', contribution: '100%', active: 'yes' },
  { url: 'ic-ostsam', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'briercrest', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'biza.digitoollab', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://tinsleyhomes.com/', platform: 'WordPress', company: 'Growmodo', contribution: '70%', active: 'yes' },
  { url: 'albertbauer', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'tenklofoten', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'bashboxing', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'seevesteralen', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'dinagenda', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://zooca.eu/', platform: 'WordPress', company: 'Growmodo', contribution: '80%', active: 'yes' },
  { url: 'https://www.zooca.no', platform: 'WordPress', company: 'Growmodo', contribution: '80%', active: 'yes' },
  { url: 'forrestbottle', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://www.smartrealtyofflorida.com/', platform: 'WordPress', company: 'Growmodo', contribution: '40%', active: 'yes' },
  { url: 'fullcafetriskele', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'markblocker', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'casamuranolasolas', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'fabbuildpro', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'freedomwarrior', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'affluencemediaagency', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'theberkshires', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'arcticseaexpeditions', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'https://myhhm.com/', platform: 'WordPress', company: 'Growmodo', contribution: '60%', active: 'yes' },
  { url: 'williamstownma', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'bishopfields', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'ndeloop', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: '18fortythree', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'staffgeek', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'folkeaksjon', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'norwayart', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'vesteraalens', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'freedomfederalbondingagency', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'besttrafficlawyer', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'bestlawreview', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'bestcasemedia', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'bestcasesite', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'vitamink2', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'kaydencepharma', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'nattopharma', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'partnersite.menaq7', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'menaq7', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'qkids', platform: 'Shopify', company: 'Growmodo', contribution: '', active: '' },
  { url: 'theagnetworkcollective', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'sw.haus', platform: 'WordPress', company: 'Growmodo', contribution: '', active: '' },
  { url: 'strongbyalex', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '90%', active: 'yes' },
  { url: 'https://actionhomerehab.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '90%', active: 'yes' },
  { url: 'https://detailedconsulting.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '90%', active: 'yes' },
  { url: 'tmrs', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'nexcess', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'nsna', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'influenceitdesign', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'bmsheetmetal', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'swconnect', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://activefloors.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '80%', active: 'yes' },
  { url: 'farronresearch', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'tracks4x4tagalong', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'northbridgenetball', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'northsnetball', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://ausbettips.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '95%', active: 'yes' },
  { url: 'probizagents', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'retailtherapygroup', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://www.drfootsolutions.com.au', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '40%', active: 'yes' },
  { url: 'fnieducation', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://pacer.solutions/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '80%', active: 'yes' },
  { url: 'https://samian.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '100%', active: 'yes' },
  { url: 'loyell', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: '360buildingandcarpentry', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'egisretail', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://chessindustries.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '80%', active: 'yes' },
  { url: 'lms-drafting', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'heater-hire', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://airconditionerhire.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '90%', active: 'yes' },
  { url: 'agileequipment', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'elitecompliance', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://kmelectric.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '10%', active: 'yes' },
  { url: 'noq.zone', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://active8group.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://boltelectrics.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '40%', active: 'yes' },
  { url: 'deadlyscience', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'bbqinabox', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'ikigaiwealth', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'latinmotion', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'oliverpineda.dance', platform: 'Wix', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://safehomepestcontrol.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '90%', active: 'yes' },
  { url: 'https://minchinburymanor.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '100%', active: 'yes' },
  { url: 'whjru', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://balboacorporate.com/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '100%', active: 'yes' },
  { url: 'wiacandles', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'http://endlessopportunities.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '90%', active: 'yes' },
  { url: 'http://jobsontime.com.au', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '100%', active: 'yes' },
  { url: 'https://southcoastblaze.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '100%', active: 'yes' },
  { url: 'https://gahermes.com.au/', platform: 'HTML', company: 'Net Fusion Technology', contribution: '100%', active: 'yes' },
  { url: 'underseaputtandplay', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'ourcow', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'lollyswagman', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'centrewaycellars', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'freelancereps', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://vacationcareaustralia.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '60%', active: 'yes' },
  { url: 'outdoo', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://precisionhail.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '80%', active: 'yes' },
  { url: 'clearbraaustralia', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'egislegal', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'bizc', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'devwiz', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'havencafe', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'remassagehealth', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'wallascleaning', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'haigenbamford', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'lindsaygibson', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'webinfobd', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'forestrangersfc', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'peterbrackstone', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://order4me.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'beewellaustralia', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://www.ivygrowthpartners.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '30%', active: 'yes' },
  { url: 'sqtaa.online', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'medallionfinancial', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'betsbandb', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'wavelengthharbourcruises', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'http://www.fyffedesignservices.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '30%', active: 'yes' },
  { url: 'actnowgc', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'lushbnb', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'christoarchitects', platform: 'HTML', company: 'Net Fusion Technology', contribution: '100%', active: 'yes' },
  { url: 'visionhomesrealestate', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'nextar', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'lugarnoshoppingvillage', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'lanceroconsulting', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'stemswithstyle', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'mortgageoptionshq', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'girlsandguys', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'gopillow', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://sleepkeeper.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '80%', active: 'yes' },
  { url: 'manybusyhands', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'avasoftware', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'southeastqldexpo', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'roomi.digital', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'lamr', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'modeltrainshow', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'people2business', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'freestyleadventuretravel', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'sydneywigservices', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'stuartplumbing', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'alexanderroastery', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'totaltax', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'totalsuperannuation', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'whispering-words-of-wisdom', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'sparksalive', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'ssentertainment', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'searchkenya', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'rocketmeatswine', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'fabulousfamilybistrofunctions', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'windowtreatments', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'meatinc', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'superiorrefinish', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'oznatives', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'loganhighwaytohell', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'logancountrysafecity', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'cafecorner', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'yourfitnesstoolbox', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'neatasgardeningservices', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'localbiznetworkinggroups', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'loganbusinessexpo', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://fpcu.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '100%', active: 'yes' },
  { url: 'jonsa', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'getbetterphysiotherapy', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'beckerpumps', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'batind', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'orangegroupco', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'orangesupermarket', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'cafeatbayliss', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'samuelgphotographyfundraiser', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'yarrafit', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'bestprofessionalfinance', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'organicpestcontrol', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://quikstart.website/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '100%', active: 'yes' },
  { url: 'cadvanceddesign', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'pioneerfinance', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'influenceit', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://enlivenremedialmassage.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '100%', active: 'yes' },
  { url: 'ninisville', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'readyloans', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'acumenasmgroup', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'hotwatermaintenancenorthernbeaches', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'arklinnoffices', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'allaboutdetailing', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'australianpipebandsupplies', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'maximusindustrial', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://baulkhamhillsphysio.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '100%', active: 'yes' },
  { url: 'kcac', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://apbc.org.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '100%', active: 'yes' },
  { url: 'arklinnlimited', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'differentthreads', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'votsport', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'sportsbox', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://sydneyconference.com.au/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '100%', active: 'yes' },
  { url: 'seniorspathway', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'utssparksnetball', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'havenhotel', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'hugjumbuck', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'https://hjugg.com/', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '100%', active: 'yes' },
  { url: 'netfusiontechnology', platform: 'WordPress', company: 'Net Fusion Technology', contribution: '', active: '' },
  { url: 'royalsprings', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'zenviron', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: '8lakeairecircuit', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'adam-purcell', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'gophysio', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'rlpelectric', platform: 'WordPress', company: 'Glue Digital', contribution: '30%', active: 'yes' },
  { url: 'crossfithorizons', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'sovereigncitycrossfit', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'centralcoast', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'ozmining', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: '246dental', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'urbanskinandbeauty', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'premierteambuilding', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'samschmarr', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'sitesafetynsw', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'newcastleroofrail', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'getaflyer', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'https://www.newcastleconnections.com.au/', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'firstpeoplefoundation', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'unexpectedexit', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'ceassa', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'entech-roadshow', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'vllpartners', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'sectechroadshow', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'igniteinternship2018', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'securityelectronicsandnetworks', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'buddyrider', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'vlcpartners', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'thesuppstop', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'loveourlivinglakes', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'walterstours', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'thegatheringfolk', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'https://earthconnect-australia.com/', platform: 'WordPress', company: 'Glue Digital', contribution: '100%', active: 'yes' },
  { url: 'lyallbuickfurniture', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'mcdonaldautomotives', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'gemaker', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'northlakessalvos', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'smdfit', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'https://www.evergreenec.com.au/', platform: 'WordPress', company: 'Glue Digital', contribution: '100%', active: 'yes' },
  { url: 'farmmachinesales', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'aurablue', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'mobilestagez', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'opportunitycambodia', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'positiveperceptions', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'newcastlewhiteboards', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'securityandgovernmentexpo', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'chpn', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'cxmagblog', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'cxevents', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'adammaddison', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'digitalgoose', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'no-digdepo', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'smiledealers', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'vtax.online', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'atevents', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'entech', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'windsorblinds', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'rushmentoring', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'kingdomworks', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'regionalprocurement', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'poochiesdelights', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'beyondtheparty', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'beyondsl', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'https://gradabuilding.com.au/', platform: 'WordPress', company: 'Glue Digital', contribution: '100%', active: 'yes' },
  { url: 'https://torontosmash.com.au/', platform: 'WordPress', company: 'Glue Digital', contribution: '100%', active: 'yes' },
  { url: 'flexfitmeals', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'thewolfpackmrs', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'nelsonbaybreeze', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'jupiterlawcenter', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'ictechroadshow', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'cx-tv', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'juliusmedia', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'tilerescue', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'wildfireyouth', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'officeorg', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'customcubbies', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'lancreation', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'https://digitalsignage-australia.com.au/', platform: 'WordPress', company: 'Glue Digital', contribution: '80%', active: 'yes' },
  { url: 'streetsafesalvos', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'drophouse', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'https://vision2watch.com.au/', platform: 'WordPress', company: 'Glue Digital', contribution: '30%', active: 'yes' },
  { url: 'arkivebynoah', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'antennawizards', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'alisonbuttenshaw', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'aetherinsurance', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'advantageplumbingsolutions', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'harperpropertyagents', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'tumblonghills', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'southcardiff', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'reflectionscards', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'felks', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'northlakescarols', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'officeorg-furniture', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'playgroundspark', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'https://totalvenue.com.au/', platform: 'WordPress', company: 'Glue Digital', contribution: '100%', active: 'yes' },
  { url: 'shotters', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'https://ezyflo.com/', platform: 'WordPress', company: 'Glue Digital', contribution: '100%', active: 'yes' },
  { url: 'intriguevideoseo', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'thegorillapit', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'groww.church', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'groww.digital', platform: 'WordPress', company: 'Glue Digital', contribution: '', active: '' },
  { url: 'https://gluedigital.com.au/', platform: 'WordPress', company: 'Glue Digital', contribution: '100%', active: 'yes' },
  { url: 'onwarditc', platform: 'WordPress', company: 'Capital Tech Co', contribution: '', active: '' },
  { url: 'kravmagasma', platform: 'WordPress', company: 'Capital Tech Co', contribution: '', active: '' },
  { url: 'electrolysis', platform: 'WordPress', company: 'Capital Tech Co', contribution: '', active: '' },
  { url: 'gemsparties', platform: 'WordPress', company: 'Capital Tech Co', contribution: '', active: '' },
  { url: 'themileagemarket', platform: 'WordPress', company: 'Capital Tech Co', contribution: '', active: '' },
  { url: 'yyzmiles', platform: 'WordPress', company: 'Capital Tech Co', contribution: '', active: '' },
  { url: 'capitaltechco', platform: 'WordPress', company: 'Capital Tech Co', contribution: '', active: '' },
  { url: 'onwarditc', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'titusvillelutherans', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'zingrealty', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'http://antlerrecords.com/', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'http://www.idltravel.com/', platform: 'WordPress', company: 'Powered', contribution: '30%', active: 'yes' },
  { url: 'diamondland', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'shulsharela', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'azwintech', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'thecallowayfoundation', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'naturesbeautybrands', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'extremetransportation', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'mayatelsystems', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'pennsylvania-roofing', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'thepottersworkshop', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'intranetneeds', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'absoluteheatingandairconditioning', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'dimensionziplines', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'theoakparkgroup', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'championsroom', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'midnightshealing', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'schoolforvegas', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'oncallreality', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'solarvision', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'happypedident', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'almaza', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'sweetdreamz', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'myvideoresume', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'jonnyritz', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'northwoodscenter', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'sarahfaithorganics', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'greencupcarwash', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'musicgroup', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'thepennquarter', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'phinder', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'carsafety', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'enrightcompany', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'pixoplustech', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'rhdraftsense', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'upscalefashiondesign', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'fashionforplay', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'diamondscoaching', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
  { url: 'enigmas', platform: 'WordPress', company: 'Powered', contribution: '', active: '' },
]
